repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: flake8
-   repo: git://github.com/skorokithakis/pre-commit-mypy
    rev: v0.701
    hooks:
    - id: mypy
      args: [-s]
